<?php echo $this->doctype(); ?>
<html>
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Nutrifami')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        $version = '1.1.15';
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/circle.css?'.$version))
                ->prependStylesheet($this->basePath('css/style.css?'.$version))
                ->prependStylesheet($this->basePath('css/font-awesome.min.css?'.$version))
                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css?'.$version))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css?'.$version))
        ?>
        <link href='https://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>

    </head>

    <body ng-app="NutrifamiWeb">

    <ng-view>
        <?php echo $this->content; ?>
    </ng-view>
    <!-- Scripts -->
    <?php
    echo $this->headScript()
            ->prependFile($this->basePath('js/nutrifami.js?'.$version))
            ->prependFile($this->basePath() . 'https://sdk.amazonaws.com/js/aws-sdk-2.3.15.min.js')
            ->prependFile($this->basePath('js/filters/filters.js?'.$version))
            ->prependFile($this->basePath('js/directives/narrador.drt.js?'.$version))
            ->prependFile($this->basePath('js/directives/goClick.drt.js?'.$version))
            ->prependFile($this->basePath('js/directives/leccionInfo.drt.js?'.$version))
            ->prependFile($this->basePath('js/directives/moduloInfo.drt.js?'.$version))
            ->prependFile($this->basePath('js/modals/nc_salir.modal.js?'.$version))
            ->prependFile($this->basePath('js/modals/diploma.modal.js?'.$version))
            ->prependFile($this->basePath('js/modals/compras.modal.js?'.$version))
            ->prependFile($this->basePath('js/modals/tips.modal.js?'.$version))
            ->prependFile($this->basePath('js/modals/feedbackUnidad.modal.js?'.$version))
            ->prependFile($this->basePath('js/modals/registro.modal.js?'.$version))
            ->prependFile($this->basePath('js/modals/login.modal.js?'.$version))
            ->prependFile($this->basePath('js/services/nutricompraService.js?'.$version))
            ->prependFile($this->basePath('js/services/tipsService.js?'.$version))
            ->prependFile($this->basePath('js/services/capacitacionService.js?'.$version))
            ->prependFile($this->basePath('js/services/comprasService.js?'.$version))
            ->prependFile($this->basePath('js/services/anchorSmootScrollService.js?'.$version))
            ->prependFile($this->basePath('js/services/AuthenticationService.js?'.$version))
            ->prependFile($this->basePath('js/services/perfilService.js?'.$version))
            ->prependFile($this->basePath('js/services/usuarioService.js?'.$version))
            ->prependFile($this->basePath('js/controllers/nc_jugarTerminarController.js?'.$version))
            ->prependFile($this->basePath('js/controllers/nc_jugarResumenController.js?'.$version))
            ->prependFile($this->basePath('js/controllers/nc_jugarController.js?'.$version))
            ->prependFile($this->basePath('js/controllers/nc_comoJugarController.js?'.$version))
            ->prependFile($this->basePath('js/controllers/nc_homeController.js?'.$version))
            ->prependFile($this->basePath('js/controllers/tipsModulosController.js?'.$version))
            ->prependFile($this->basePath('js/controllers/tipsController.js?'.$version))
            ->prependFile($this->basePath('js/controllers/progresoController.js?'.$version))
            ->prependFile($this->basePath('js/controllers/misComprasIntroController.js?'.$version))
            ->prependFile($this->basePath('js/controllers/misComprasGrupoController.js?'.$version))
            ->prependFile($this->basePath('js/controllers/misComprasController.js?'.$version))
            ->prependFile($this->basePath('js/controllers/sobreController.js?'.$version))
            ->prependFile($this->basePath('js/controllers/landingController.js?'.$version))
            ->prependFile($this->basePath('js/controllers/template/headerController.js?'.$version))
            ->prependFile($this->basePath('js/controllers/leccionTerminadaController.js?'.$version))
            ->prependFile($this->basePath('js/controllers/unidadController.js?'.$version))
            ->prependFile($this->basePath('js/controllers/moduloController.js?'.$version))
            ->prependFile($this->basePath('js/controllers/loginController.js?'.$version))
            ->prependFile($this->basePath('js/controllers/editarPerfilController.js?'.$version))
            ->prependFile($this->basePath('js/controllers/perfilController.js?'.$version))
            ->prependFile($this->basePath('js/controllers/capacitacionController.js?'.$version))
            ->prependFile($this->basePath('js/app.js?'.$version))
            ->prependFile($this->basePath('lib/pdfmake/build/vfs_fonts.js?'.$version))
            ->prependFile($this->basePath('lib/pdfmake/build/pdfmake.js?'.$version))
            ->prependFile($this->basePath('lib/html2canvas/build/html2canvas.js?'.$version))
            ->prependFile($this->basePath('lib/angular-socialshare/dist/angular-socialshare.min.js?'.$version))
            ->prependFile($this->basePath('lib/js-md5/src/md5.js?'.$version))
            ->prependFile($this->basePath('lib/angular-loading-overlay/dist/angular-loading-overlay.js?'.$version))
            ->prependFile($this->basePath('lib/angular-bootstrap/ui-bootstrap-tpls.min.js?'.$version))
            ->prependFile($this->basePath('lib/angular-bootstrap/ui-bootstrap.min.js?'.$version))
            ->prependFile($this->basePath('lib/jquery/dist/jquery.min.js?'.$version))
            ->prependFile($this->basePath('lib/angular-animate/angular-animate.min.js?'.$version))
            ->prependFile($this->basePath('lib/angular-audio/app/angular.audio.js?'.$version))
            ->prependFile($this->basePath('lib/angular-cookies/angular-cookies.js?'.$version))
            ->prependFile($this->basePath('lib/angular-route/angular-route.js?'.$version))
            ->prependFile($this->basePath('lib/angular/angular.js?'.$version))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9'))
            ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9'));
    ?>

    <script>
(function(i, s, o, g, r, a, m) {
    i['GoogleAnalyticsObject'] = r;
    i[r] = i[r] || function() {

        (i[r].q = i[r].q || []).push(arguments)
    }, i[r].l = 1 * new Date();
    a = s.createElement(o),

        m = s.getElementsByTagName(o)[0];
    a.async = 1;
    a.src = g;
    m.parentNode.insertBefore(a, m)

})(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

ga('create', 'UA-88108666-1', 'auto');
ga('send', 'pageview');
</script>
</body>
</html>